version: '3.3'

services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./backend:/var/www/${PROJECT_NAME}
    ports:
      - 127.0.0.1:8080:80
    links:
      - php
    networks:
      main:
        ipv4_address: 178.21.1.2

  php:
#    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: docker/php-fpm.dockerfile
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-php
    volumes:
      - ./backend:/var/www/${PROJECT_NAME}
      - ./docker/php-ini:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    links:
      - mysql
    networks:
      main:
        ipv4_address: 178.21.1.3

  mysql:
    build:
      context: .
      dockerfile: docker/mysql.dockerfile
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-mysql
    volumes:
      - ./Makefile:/Makefile
    ports:
      - 53307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${PROJECT_NAME}_db
    networks:
      main:
        ipv4_address: 178.21.1.4

networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: "178.21.1.0/24"